version: "3.2"
services:
    auditor:
        build: ./docker/image-auditor
        image: res/auditor
        ports:
            - "2205:2205"
            - "3030:3030"
    musician:
        build: ./docker/image-musician
        image: res/musician
    monitor:
        build: ./docker/image-monitor
        image: res/monitor
        ports:
            - "5000:5000"
